language: php

php:
  - '7.1'

before_install:
  - |
    git checkout -q HEAD^1
    git tag -f base
    git fetch -q origin +refs/pull/$TRAVIS_PULL_REQUEST/head
    git checkout -qf FETCH_HEAD
    git tag -f feature
    git tag -f refactor HEAD^1

install:
  - composer update

before_script:
  - mkdir -p build/logs
  - |
    validate_feature() {
      MODIFIED_FILES=$(git diff --name-only --diff-filter=MRTXB refactor..feature)
      php validate Feature $MODIFIED_FILES
    }
  - |
    validate_refactoring() {
      MODIFIED_FILES=$(git diff --name-only --diff-filter=ACDMRTUXB base..feature)
      php validate Refactoring $MODIFIED_FILES
    }

script:
  - phpunit --disable-coverage-ignore
  - validate_feature
  - git checkout refactor
  - phpunit --disable-coverage-ignore --exclude-group new
  - validate_refactoring
